### ISSUE TITLE
Internal link not showing up in graph view and backlinks

### ISSUE THREAD

**Issue by Masktial** [alx-plugins/table-extended#2]
谢谢大佬~
![image](https://user-images.githubusercontent.com/82996431/120573738-ad5e5380-c450-11eb-88cc-c3d30a14b713.png)

如图[[汇总]]没有在图谱中显示

**Comment by AidenLx** [comment]
现在可以把代码块换成这样就没问题了：
```md
-tx-
<接下来是你的表格>
```
